INSERT OR IGNORE INTO game_mode(id,
                                eid,
                                name,
                                description,
                                draft_value,
                                player_count,
                                income,
                                reinforcements_enabled,
                                game_id,
                                version,
                                created_by_sub,
                                created_at,
                                updated_at,
                                deleted_at)
VALUES
  (1,
   'a1b2c3d4-0001-4000-8000-000000000001',
   'Land Battle',
   'A standard pitched battle between two armies on open terrain.',
   12400,
   2,
   1000,
   0,
   1,
   1,
   'f0ce7395-a57f-41e9-ade0-fd13bafc058f',
   STRFTIME('%Y-%m-%dT%H:%M:%fZ','now'),
   STRFTIME('%Y-%m-%dT%H:%M:%fZ','now'),
   null),
  (2,
   'a1b2c3d4-0002-4000-8000-000000000002',
   'Domination',
   'A battle fought over capture points. Armies earn victory points by holding objectives.',
   9000,
   2,
   1000,
   1,
   1,
   1,
   'f0ce7395-a57f-41e9-ade0-fd13bafc058f',
   STRFTIME('%Y-%m-%dT%H:%M:%fZ','now'),
   STRFTIME('%Y-%m-%dT%H:%M:%fZ','now'),
   null);
