-- Generated by rpfm-scraper.  Do not hand-edit — re-run the scraper.
-- Sourced from `unit_stats_land_experience_bonuses_tables`.  The engine
-- formula is: adjusted_cost = round(base_cost * cost_multiplier) + fixed_cost.
-- One global row per veteran rank (0-9); applies to every unit.
INSERT OR REPLACE INTO unit_level_cost(level, fixed_cost, cost_multiplier, fatigue, melee_cp, missile_cp) VALUES
  (0,  0, 1.00,  0,   0,   0),
  (1, 11, 1.03,  0,  26,  26),
  (2, 22, 1.06,  0,  51,  51),
  (3, 33, 1.09, -1,  77,  77),
  (4, 44, 1.12, -1, 102, 102),
  (5, 55, 1.15, -2, 128, 128),
  (6, 66, 1.18, -2, 154, 154),
  (7, 77, 1.21, -3, 179, 179),
  (8, 88, 1.24, -3, 205, 205),
  (9, 99, 1.27, -4, 230, 230);
