(ns com.devereux-henley.rpfm-scraper.unit-level-cost-seed
  (:require
   [clojure.string :as str]))

(def ^:private expected-levels (set (range 0 10)))

(defn- ->level [v]
  (cond
    (integer? v) v
    (string? v)  (try (Integer/parseInt v) (catch Exception _ nil))
    :else        nil))

(defn- row-tuple [row]
  (let [lvl (->level (get row "xp_level"))
        fc  (some-> (get row "mp_fixed_cost") int)
        mul (some-> (get row "mp_experience_cost_multiplier") double)
        fat (or (some-> (get row "fatigue") int) 0)
        mcp (or (some-> (get row "additional_melee_cp") double) 0.0)
        rcp (or (some-> (get row "additional_missile_cp") double) 0.0)]
    (when (and lvl fc mul) [lvl fc mul fat mcp rcp])))

(defn- format-row [[lvl fc mul fat mcp rcp] last?]
  (format "  (%d, %d, %s, %d, %s, %s)%s"
          lvl fc (str mul) fat (str mcp) (str rcp)
          (if last? ";" ",")))

(defn generate-unit-level-cost-seed
  "Render the level-cost seed from `unit_stats_land_experience_bonuses_tables` rows.
  Returns {:content sql, :rows N, :missing-levels #{...}} where missing-levels lists
  any expected rank (0-9) absent from the input — strict mode treats this as a fault."
  [rows]
  (let [tuples      (->> rows (keep row-tuple) (sort-by first))
        seen-levels (set (map first tuples))
        missing     (set (remove seen-levels expected-levels))
        n           (count tuples)
        header      ["-- Generated by rpfm-scraper.  Do not hand-edit — re-run the scraper."
                     "-- Sourced from `unit_stats_land_experience_bonuses_tables`.  The engine"
                     "-- formula is: adjusted_cost = round(base_cost * cost_multiplier) + fixed_cost."
                     "-- One global row per veteran rank (0-9); applies to every unit."
                     "INSERT OR REPLACE INTO unit_level_cost(level, fixed_cost, cost_multiplier, fatigue, melee_cp, missile_cp) VALUES"]
        body        (map-indexed (fn [i t] (format-row t (= (inc i) n))) tuples)
        content     (str (str/join "\n" (concat header body)) "\n")]
    {:content        content
     :rows           n
     :missing-levels missing}))
